### ISSUE TITLE
App doesn't start due to locale error

### ISSUE THREAD

**Issue by FakeShemp** [flathub/com.github.unrud.VideoDownloader#3]
On Ubuntu 20.04 I get an error when trying to start the app.
```
$ flatpak run com.github.unrud.VideoDownloader
Traceback (most recent call last):
  File "/app/bin/video-downloader", line 36, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.7/locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by Unrud** [comment]
Should be fixed in version 0.5.5.
